config/routes.rb
Rails.application.routes.draw do
  resources :maintenance_logs
  devise_for :users
  root "logs#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/maintenance_log.rb
class MaintenanceLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maintenance_logs_controller.rb
class MaintenanceLogsController < ApplicationController
  before_action :set_maintenance_log, only: %i[ show edit update destroy ]

  # GET /maintenance_logs or /maintenance_logs.json
  def index
    @maintenance_logs = MaintenanceLog.all
  end

  # GET /maintenance_logs/1 or /maintenance_logs/1.json
  def show
  end

  # GET /maintenance_logs/new
  def new
    @maintenance_log = MaintenanceLog.new
  end

  # GET /maintenance_logs/1/edit
  def edit
  end

  # POST /maintenance_logs or /maintenance_logs.json
  def create
    @maintenance_log = MaintenanceLog.new(maintenance_log_params)

    respond_to do |format|
      if @maintenance_log.save
        format.html { redirect_to maintenance_log_url(@maintenance_log), notice: "Maintenance log was successfully created." }
        format.json { render :show, status: :created, location: @maintenance_log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance_logs/1 or /maintenance_logs/1.json
  def update
    respond_to do |format|
      if @maintenance_log.update(maintenance_log_params)
        format.html { redirect_to maintenance_log_url(@maintenance_log), notice: "Maintenance log was successfully updated." }
        format.json { render :show, status: :ok, location: @maintenance_log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_logs/1 or /maintenance_logs/1.json
  def destroy
    @maintenance_log.destroy

    respond_to do |format|
      format.html { redirect_to maintenance_logs_url, notice: "Maintenance log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_log
      @maintenance_log = MaintenanceLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_log_params
      params.require(:maintenance_log).permit(:title, :description, :date, :hoursUntilService)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maintenance_logs_helper.rb
module MaintenanceLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BicycleMaintenanceLogV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text float-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/logs/_form.html.erb
<style>

.center {
  margin: auto;
  width: 60%;
  padding: 10px; 
}

.divBlackBorder {
  width: 320px;
  padding: 10px;
  border: 5px solid gray;
  margin: 0;

}

</style>



<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="divBlackBorder">

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/logs/show.html.erb
<!DOCTYPE HTML>
<html>
<head>

<p id="notice"><%= notice %></p>

<style>


.divBlackBorder {
  width: 320px;
  padding: 10px;
  border: 5px solid gray;
  margin: 0;

}

a:link {
  background-color: yellow;
}

a:visited {
  background-color: cyan;
}

a:hover {
  background-color: lightgreen;
}

a:active {
  background-color: hotpink;
} 

body {
    background-color: rgb(240, 255, 255);
}


</style>
</head>
<body>

<h1> <u>Please update your log to the most accurate date and any other notes</u> </h1>

<div class= "divBlackBorder">
<p>
  <strong>Title:</strong>
  <%= @log.title %>
</p>
</div>

<div class= "divBlackBorder">
<p>
  <strong>Description:</strong>
  <%= @log.description %>
</p>
</div>

<div class= "divBlackBorder">
<p>
  <strong>Date:</strong>
  <%= @log.date %>
</p>
<p><u> Time Remaining:</u><p/>

<p id="demo"></p>

<script>
// Set the date we're counting down to
var countDownDate = new Date("May 12, 2023 15:37:25").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();
    
  // Find the distance between now and the count down date
  var distance = countDownDate - now;
    
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
  // Output the result in an element with id="demo"
  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";
    
  // If the count down is over, write some text 
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>

</div>


<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>

</body>
</html>

app/views/maintenance_logs/_form.html.erb
<%= form_with(model: maintenance_log) do |form| %>
  <% if maintenance_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maintenance_log.errors.count, "error") %> prohibited this maintenance_log from being saved:</h2>

      <ul>
        <% maintenance_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date %>
  </div>

  <div class="field">
    <%= form.label :hoursUntilService %>
    <%= form.number_field :hoursUntilService %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maintenance_logs/edit.html.erb
<h1>Editing Maintenance Log</h1>

<%= render 'form', maintenance_log: @maintenance_log %>

<%= link_to 'Show', @maintenance_log %> |
<%= link_to 'Back', maintenance_logs_path %>

app/views/maintenance_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maintenance Logs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Hoursuntilservice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maintenance_logs.each do |maintenance_log| %>
      <tr>
        <td><%= maintenance_log.title %></td>
        <td><%= maintenance_log.description %></td>
        <td><%= maintenance_log.date %></td>
        <td><%= maintenance_log.hoursUntilService %></td>
        <td><%= link_to 'Show', maintenance_log %></td>
        <td><%= link_to 'Edit', edit_maintenance_log_path(maintenance_log) %></td>
        <td><%= link_to 'Destroy', maintenance_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maintenance Log', new_maintenance_log_path %>

app/views/maintenance_logs/new.html.erb
<h1>New Maintenance Log</h1>

<%= render 'form', maintenance_log: @maintenance_log %>

<%= link_to 'Back', maintenance_logs_path %>

app/views/maintenance_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @maintenance_log.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @maintenance_log.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @maintenance_log.date %>
</p>

<p>
  <strong>Hoursuntilservice:</strong>
  <%= @maintenance_log.hoursUntilService %>
</p>

<%= link_to 'Edit', edit_maintenance_log_path(@maintenance_log) %> |
<%= link_to 'Back', maintenance_logs_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/work_logs/_form.html.erb
<%= form_with(model: work_log) do |form| %>
  <% if work_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_log.errors.count, "error") %> prohibited this work_log from being saved:</h2>

      <ul>
        <% work_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date %>
  </div>

  <div class="field">
    <%= form.label :hoursUntilServiceDue %>
    <%= form.number_field :hoursUntilServiceDue %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>